# Dockerfile from crossbar docker/disclose example

FROM node:11-alpine as build-deps
#WORKDIR /Users/smohanra/Desktop/crescentMockup
#WORKDIR /home/smohanra/crescent-frontend
COPY package.json .
COPY package-lock.json .

RUN npm install --no-save
