FROM ubuntu:19.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y \
            python \
            python-pip \ 
            nodejs \
            npm 

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE 3000
CMD ["npm", "run", "start"]
