version: "2"

services: 
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react/build:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/errors:/var/log/nginx

    depends_on:
      - server
      - graphene
    command: nginx -g "daemon off;"
