import React, {useState, useEffect} from 'react';

import {Menu, Card, Header, Segment, Button, Grid, Modal, Label, Divider, Icon, Image, Popup} from 'semantic-ui-react'

import UHN from './UHN.png'
import SK from './SK.png'
import GC from './GC.jpeg'
import MBD from './MBD.jpg'

import * as R from 'ramda'
import * as RA from 'ramda-adjunct'

import withRedux from '../../redux/hoc'

const CrescentIcon = () => (
  <Icon.Group style={{marginTop: -3}} >
    <Icon name='cloud' size='big'  />
    <Icon name='moon' size='small' inverted style={{marginTop: 2, marginLeft: -2}} />
  </Icon.Group>
)

const InfoModal = () => (
  <Modal
    trigger={<Button color='black' floated='right' basic icon><Icon size='large' name='info circle' /></Button>}
  >
    <Modal.Content>
    <Header content='Help'/>

      A quick walkthrough of accessing and exploring public datasets can be found on <a href='https://youtu.be/KK4Xc6SBSSY' target='_blank'>Youtube.</a> 

    <Divider/>
    <Header content='Contact Us'/>

      To reach the crescent.cloud portal-dev team, please email <a href='mailto:crescent@uhnresearch.ca'>crescent@uhnresearch.ca</a> using these template forms to: <a href='https://github.com/pughlab/crescent/blob/master/.github/ISSUE_TEMPLATE/bug_report.md' target='_blank'>report bugs</a> or <a href='https://github.com/pughlab/crescent/blob/master/.github/ISSUE_TEMPLATE/feature_request.md' target='_blank'>request features.</a> This can also be done on our <a href='https://github.com/pughlab/crescent' target='_blank'>Github.</a>

    <Divider/>

    <Header content='About Us'/>
      CanceR Single Cell ExpressioN Toolkit (CReSCENT) is a scalable and standardized set of novel algorithmic methods, tools, and a data portal deployed on cloud computing infrastructure. To allow comparison of cells in cancerous and healthy tissues, the system will aggregate single-cell genomic data generated by cancer researchers and connect them to international reference data generated by experts from around the world. This data sharing and aggregation system is a key differentiating factor in CReSCENT that will increase researcher productivity by accelerating execution and comparison of computational methods, as well as providing contextual data for understanding how cells behave within tumour tissues. CReSCENT is available under an open source license via <a href='https://github.com/pughlab/crescent/blob/master/LICENSE' target='_blank'>Github.</a>
    <Divider/>
    <Header content='Supported By'/>
      <Grid>
        <Grid.Row columns={4}>
          <Grid.Column>
            <Image src={UHN}/>
          </Grid.Column>
          <Grid.Column>
            <Image src={SK}/>
          </Grid.Column>
          <Grid.Column>
            <Image src={GC}/> 
          </Grid.Column>
          <Grid.Column>
            <Image src={MBD}/>
          </Grid.Column>
        </Grid.Row>

      </Grid>



    </Modal.Content>
  </Modal>
)

const MenuComponent = withRedux(({
  app: {
    user,
    project,
    run,
    view: {main}
  },
  actions: {
    // logout,
    setRun,
    toggleProjects,
    toggleRuns,
    toggleLogin
  }
}) => {
  const isMainView = R.equals(main)
  return (
    <Segment attached='top' style={{height: '10%'}} as={Grid}>
      <Grid.Column width={3}>
        <Button.Group fluid widths={3} size='small'>
          <Button icon basic color='black'
            disabled={isMainView('projects')}
            onClick={() => 
              isMainView('login') ? toggleProjects()
              : isMainView('vis') ? toggleRuns()
              : isMainView('runs') ? toggleProjects()
              : isMainView('projects') ? toggleProjects() : null
            }
          >
            <Icon name='double angle left' size='large'/>
          </Button>
          <Button icon basic color='black'
            onClick={() => toggleProjects()}
            disabled={isMainView('projects')}
          >
            <Icon name='archive' size='large'/>
          </Button>
          <Button icon basic color='black'
            onClick={() => toggleRuns()}
            disabled={R.isNil(project) || R.and(RA.isNotNil(project), isMainView('projects'))}
          >
            <Icon name='paper plane' size='large'/>
          </Button>
        </Button.Group>
      </Grid.Column>
      <Grid.Column width={2}>

      </Grid.Column>
      <Grid.Column width={6} verticalAlign='middle'>
        {
          isMainView('projects')  ? 
            <Header textAlign='center'>
            {
              RA.isNotNil(project) ?
                <Label size='large' basic icon='archive' color='black' content={R.prop('name', project)} />
              :
                <Header textAlign='center'>
                  <Icon name='archive' />
                  Select a Project
                </Header>
            }
            </Header>
          : isMainView('runs')  ?
            <Header textAlign='center'>
              <Label.Group size='large'>
                <Label icon='archive' color='black' content={R.prop('name', project)} />
                {
                  RA.isNotNil(run) &&
                  <Label icon='paper plane' basic color='black' content={R.prop('name', run)} />  
                }
              </Label.Group>
              
            </Header>
          : isMainView('login') ?
            <Header textAlign='center'>
              {
                RA.isNotNil(user) ? 
                  <>
                    <Icon name='user circle' />
                    User
                  </>
                :
                  <>
                    <Icon name='sign in' />
                    Sign In
                  </>
              }
            </Header>
          : isMainView('vis') ?
            <Header textAlign='center'>
              <Label.Group size='large'>
                <Label icon='archive' color='black' content={R.prop('name', project)} />
                <Label icon='paper plane' color='black' content={R.prop('name', run)} />
              </Label.Group>
            </Header>
          : null
        }
      </Grid.Column>
      <Grid.Column width={2}>

      </Grid.Column>
      <Grid.Column width={3} verticalAlign='middle'>
        <Button.Group fluid widths={2} size='small'>
          <InfoModal />
          <Button color='black' icon
            basic
            onClick={() => toggleLogin()}
          >
            <Icon size='large' name={'user circle'} />
          </Button>
        </Button.Group>
      </Grid.Column>
    </Segment>
  )
})

export default MenuComponent