import React, {useState, useEffect} from 'react';

import {Menu, Card, Header, Segment, Button, Grid, Modal, Label, Divider, Icon, Image} from 'semantic-ui-react'

import UHN from './UHN.png'
import SK from './SK.png'
import GC from './GC.jpeg'
import MBD from './MBD.jpg'

import * as R from 'ramda'
import * as RA from 'ramda-adjunct'

import withRedux from '../../redux/hoc'

const CrescentIcon = () => (
  <Icon.Group style={{marginTop: -3}} >
    <Icon name='cloud' size='big'  />
    <Icon name='moon' size='small' inverted style={{marginTop: 2, marginLeft: -2}} />
  </Icon.Group>
)

const InfoModal = () => (
  <Modal
    trigger={<Menu.Item><Icon size='large' name='info circle' /></Menu.Item>}
  >
    <Modal.Content>
    <Header content='Help'/>

      A quick walkthrough of accessing and exploring public datasets can be found on <a href='https://youtu.be/KK4Xc6SBSSY' target='_blank'>Youtube.</a> 

    <Divider/>
    <Header content='Contact Us'/>

      To reach the crescent.cloud portal-dev team, please email <a href='mailto:crescent@uhnresearch.ca'>crescent@uhnresearch.ca</a> using these template forms to: <a href='https://github.com/pughlab/crescent/blob/master/.github/ISSUE_TEMPLATE/bug_report.md' target='_blank'>report bugs</a> or <a href='https://github.com/pughlab/crescent/blob/master/.github/ISSUE_TEMPLATE/feature_request.md' target='_blank'>request features.</a> This can also be done on our <a href='https://github.com/pughlab/crescent' target='_blank'>Github.</a>

    <Divider/>

    <Header content='About Us'/>
      CanceR Single Cell ExpressioN Toolkit (CReSCENT) is a scalable and standardized set of novel algorithmic methods, tools, and a data portal deployed on cloud computing infrastructure. To allow comparison of cells in cancerous and healthy tissues, the system will aggregate single-cell genomic data generated by cancer researchers and connect them to international reference data generated by experts from around the world. This data sharing and aggregation system is a key differentiating factor in CReSCENT that will increase researcher productivity by accelerating execution and comparison of computational methods, as well as providing contextual data for understanding how cells behave within tumour tissues. CReSCENT is available under an open source license via <a href='https://github.com/pughlab/crescent/blob/master/LICENSE' target='_blank'>Github.</a>
    <Divider/>
    <Header content='Supported By'/>
      <Grid>
        <Grid.Row columns={4}>
          <Grid.Column>
            <Image src={UHN}/>
          </Grid.Column>
          <Grid.Column>
            <Image src={SK}/>
          </Grid.Column>
          <Grid.Column>
            <Image src={GC}/> 
          </Grid.Column>
          <Grid.Column>
            <Image src={MBD}/>
          </Grid.Column>
        </Grid.Row>

      </Grid>



    </Modal.Content>
  </Modal>
)

const MenuComponent = withRedux(({
  app: {
    user,
    project,
    run,
    view: {main, sidebar}
  },
  actions: {
    logout,
    setRun,
    toggleProjects,
    toggleRuns
  }
}) => {
  const isMainView = R.equals(main)
  return (
    <Segment attached='bottom' style={{height: '8%'}} as={Menu} size='large'>
      <Menu.Item header content={<CrescentIcon />} />
      <InfoModal />
      <Menu.Item content='Logout' onClick={() => logout()} />

      <Menu.Menu position='right'>
      {
        isMainView('vis') &&
        <Menu.Item content='Projects' onClick={() => toggleProjects()} />
      }
      {
        isMainView('vis') &&
        <Menu.Item content='Runs' onClick={() => toggleRuns()} />
      }
      {
        R.not(isMainView('vis')) && RA.isNotNil(run) && RA.isNotNil(project) && 
        // Set to current run to reset from toggle projects/runs
        <Menu.Item content='Cancel' onClick={() => setRun(run)} />
      }
      </Menu.Menu>
    </Segment>
  )
})

export default MenuComponent